project:
  type: website
  execute-dir: project
  output-dir: docs

website:
  title: "LearnB4P"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: setup.qmd
        text: Set-up

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



