project:
  type: website
  execute-dir: project
  output-dir: docs

website:
  title: "learnB4P"
  navbar:
    tools:
    - icon: github
      href: "https://github.com/stefanocoretta/learnB4P"
    left:
      - href: index.qmd
        text: Home
      - href: setup.qmd
        text: Set-up
      - text: Slides
        menu:
          - href: "slides/01_introduction.qmd"
            text: "01 - Introduction"
          - href: "slides/02_priors.qmd"
            text: "02 - Priors"
          - href: "slides/03_categorical.qmd"
            text: "03 - Categorical predictors"
          - href: "slides/04_interactions.qmd"
            text: "04 - Interactions"
          - href: "slides/05_numeric.qmd"
            text: "05 - Numeric predictors"
          - href: "slides/06_multilevel_1.qmd"
            text: "06 - Multilevel models I"

format:
  html:
    theme: solar
    css: styles.css
    toc: true

execute:
  freeze: auto

